#!/bin/bash

set -e

CONFIG_PATH="$CI_PROJECT_DIR/example.env"

sed -i "s|DEFAULT_TOKEN.*|DEFAULT_TOKEN='$DEFAULT_TOKEN'|g" "${CONFIG_PATH}"
sed -i "s|DEFAULT_QUOTE.*|DEFAULT_QUOTE='$DEFAULT_QUOTE'|g" "${CONFIG_PATH}"
sed -i "s|FAUCET_URL.*|FAUCET_URL='$FAUCET_URL'|g" "${CONFIG_PATH}"
sed -i "s|DEX_URL.*|DEX_URL='$DEX_URL'|g" "${CONFIG_PATH}"
sed -i "s|DEFAULT_CHAIN_ID.*|DEFAULT_CHAIN_ID='$DEFAULT_CHAIN_ID'|g" "${CONFIG_PATH}"
sed -i "s|BLOCKCHAIN_ENDPOINTS.*|BLOCKCHAIN_ENDPOINTS='$BLOCKCHAIN_ENDPOINTS'|g" "${CONFIG_PATH}"
